steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile',
      '-t', 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/ishwarya-101023221/myapp:$COMMIT_SHA',
      '.'
    ]

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/ishwarya-101023221/myapp:$COMMIT_SHA'
    ]

  # Deployment step
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'firstname-studentid-service',
        '--image=northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/ishwarya-101023221/myapp:$COMMIT_SHA',
        '--region=us-central1',
        '--platform=managed',
        '--allow-unauthenticated'
      ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
